name: Deploy Frontend (Vite) to VPS via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy frontend via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Добавляем путь к npm в переменную окружения
          export PATH=$PATH:/root/.nvm/versions/node/v22.15.0/bin

          # Проверяем установку node и npm
          node -v
          npm -v
          which node
          which npm

          # Переходим в директорию проекта
          cd /var/www/vkr/frontend

          # Если папка .git отсутствует, клонируем репозиторий
          if [ ! -d ".git" ]; then
            git clone https://github.com/ElamanBaiguanishev/corporate-social-network-front . 
          else
            git pull
          fi

          # Устанавливаем зависимости
          npm install

          # Устанавливаем переменную окружения для API
          export VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

          # Строим проект
          NODE_OPTIONS="--max-old-space-size=8192" npm run build
